AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Style/CommandLiteral:
  EnforcedStyle: percent_x
Style/ConcatArrayLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/WordArray:
  Enabled: false